FROM nginx:latest

#COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

COPY ./app/static/ /usr/share/nginx/html/static/
COPY ./app/media/ /usr/share/nginx/html/media/


EXPOSE 80

# Запускаем Nginx в фоновом режиме
CMD ["nginx", "-g", "daemon off;"]